feat(cicd): 백업 및 롤백 로직 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,6 +42,24 @@ jobs:
         run: |
           echo "$EC2_SSH_KEY" > ec2_key.pem
           chmod 600 ec2_key.pem
+
+      - name: Backup Previous Artifect and Log
+        env:
+          EC2_USER: ${{ secrets.EC2_USER }}
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+        run: |
+          ssh -i ec2_key.pem -o StrictHostKeyChecking=no \
+          $EC2_USER@$EC2_HOST << EOF
+            if [ -f server.jar ]; then
+              sudo mv server.jar server.bak.jar
+              echo "server.bak.jar created."
+            fi
+
+            if [ -f app.log ]; then
+              sudo mv app.log app.bak.log
+              echo "app.bak.log created."
+            fi
+          EOF
       
       - name: Transfer JAR to EC2
         env:
@@ -49,18 +67,47 @@ jobs:
           EC2_HOST: ${{ secrets.EC2_HOST }}
         run: |
           scp -i ec2_key.pem -o StrictHostKeyChecking=no \
-          build/libs/api-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/
+          build/libs/api-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/server.jar
           # TODO: The name of jar file might change. Need other way to handle this.
 
       - name: Deploy Application on EC2
         env:
-          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
           EC2_USER: ${{ secrets.EC2_USER }}
           EC2_HOST: ${{ secrets.EC2_HOST }}
         run: |
           ssh -i ec2_key.pem -o StrictHostKeyChecking=no \
           $EC2_USER@$EC2_HOST << EOF
-            pkill -f api-0.0.1-SNAPSHOT.jar || true
-            nohup java -jar /home/$EC2_USER/api-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
+            pkill -f server.jar || true
+            nohup java -jar /home/$EC2_USER/server.jar --spring.profiles.active=dev > app.log 2>&1 &
           EOF
 
+      - name: Check Application Running Status and Rollback
+        env:
+          EC2_USER: ${{ secrets.EC2_USER }}
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+        run: |
+          ssh -i ec2_key.pem -o StrictHostKeyChecking=no \
+            $EC2_USER@$EC2_HOST << EOF
+              echo 'Wait for 30 seconds for server to startup...'
+              sleep 30
+
+              curl http://localhost:8080
+              if [ $? -ne 0 ]; then
+                echo "New server startup failed."
+                echo 
+                echo "========= ERROR LOG =========="
+                cat out.log
+                echo "========== LOG END ==========="
+                echo 
+            
+                if [ -f "server.bak.jar" ]; then
+                  mv server.bak.jar server.jar
+                  echo "Backup jar recovered."
+
+                  pkill -f server.jar || true
+                  nohup java -jar /home/$EC2_USER/server.jar --spring.profiles.active=dev > app.log 2>&1 &
+                fi
+
+                exit 1
+              fi
+            EOF
